---
version: 3
default-service:
  replicas: 2
  cpu: 512m
  memory: 256Mi
services:
  - name: web
    replicas: 2
    cpu: 512m
    memory: 256Mi
    port: 80
    image: my-app:latest
  - name: api
    replicas: 2
    cpu: 512m
    memory: 256Mi
    port: 8080
    image: my-app-api:latest
  - name: worker
    replicas: 3
    cpu: 512m
    memory: 256Mi
    port: 9000
    image: my-app-worker:latest