version: 3

default-service: &default-service
  replicas: 2
  cpu: "512m"
  memory: "256Mi"

services: 
  - name: web
    <<: *default-service
    port: 80
    image: my-app:latest

  - name: api
    <<: *default-service
    port: 8080
    image: my-app-api:latest
  
  - name: worker
    <<: *default-service
    port: 9000
    image: my-app-worker:latest
    replicas: 3 